// AUTO-GENERATED by scripts/generate_ts_client.mjs from docs/openapi.yaml.
// Do not edit by hand. Run `node scripts/generate_ts_client.mjs` to regenerate.
// Covers 32 operations.

export interface ClientOptions {
  baseUrl?: string;
  token?: string;
}

export class EthosApiClient {
  readonly baseUrl: string;
  private readonly token?: string;

  constructor(opts: ClientOptions = {}) {
    this.baseUrl = (opts.baseUrl ?? "http://localhost:3000").replace(/\/$/, "");
    this.token = opts.token;
  }

  private request(url: string, method: string, body: unknown, init?: RequestInit): Promise<Response> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (this.token) headers["authorization"] = `Bearer ${this.token}`;
    return fetch(url, {
      method,
      headers: { ...headers, ...(init?.headers as Record<string, string>) },
      body: body === undefined ? undefined : JSON.stringify(body),
      ...init,
    });
  }

  /** GET /health */
  getHealth(init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/health`, "GET", undefined, init);
  }

  /** GET /ready */
  getReady(init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/ready`, "GET", undefined, init);
  }

  /** GET /api/vaults/{vault_id}/reminder-preferences */
  getPreferences(vaultId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/reminder-preferences`, "GET", undefined, init);
  }

  /** POST /api/vaults/{vault_id}/reminder-preferences */
  setPreferences(vaultId: string, body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/reminder-preferences`, "POST", body, init);
  }

  /** POST /api/notifications/register */
  registerDeviceToken(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/notifications/register`, "POST", body, init);
  }

  /** PUT /api/notifications/preferences */
  updateNotificationPreferences(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/notifications/preferences`, "PUT", body, init);
  }

  /** GET /api/notifications/unsubscribe */
  unsubscribeReminders(init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/notifications/unsubscribe`, "GET", undefined, init);
  }

  /** POST /api/ttl-insurance/purchase */
  purchaseTtlInsurance(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/ttl-insurance/purchase`, "POST", body, init);
  }

  /** GET /api/ttl-insurance/vaults/{vault_id} */
  getTtlInsurancePolicy(vaultId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/ttl-insurance/vaults/${encodeURIComponent(vaultId)}`, "GET", undefined, init);
  }

  /** POST /api/vaults/search */
  searchVaults(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/search`, "POST", body, init);
  }

  /** POST /api/vaults/compare */
  compareVaults(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/compare`, "POST", body, init);
  }

  /** GET /api/vaults/{vault_id}/export */
  exportVault(vaultId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/export`, "GET", undefined, init);
  }

  /** GET /api/vaults/{vault_id}/analytics */
  getVaultAnalytics(vaultId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/analytics`, "GET", undefined, init);
  }

  /** POST /api/vaults/{vault_id}/share */
  shareVault(vaultId: string, body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/share`, "POST", body, init);
  }

  /** POST /api/vaults/{vault_id}/backup */
  createVaultBackup(vaultId: string, body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/backup`, "POST", body, init);
  }

  /** GET /api/vaults/{vault_id}/backup */
  listVaultBackups(vaultId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/backup`, "GET", undefined, init);
  }

  /** POST /api/vaults/restore */
  restoreVaultBackup(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/restore`, "POST", body, init);
  }

  /** GET /api/vaults/{vault_id}/simulate-release */
  simulateVaultRelease(vaultId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/api/vaults/${encodeURIComponent(vaultId)}/simulate-release`, "GET", undefined, init);
  }

  /** POST /timeseries/ingest */
  ingestTimeSeriesPoint(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/timeseries/ingest`, "POST", body, init);
  }

  /** POST /timeseries/query */
  queryTimeSeries(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/timeseries/query`, "POST", body, init);
  }

  /** POST /timeseries/{series}/compress */
  compressTimeSeries(series: string, body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/timeseries/${encodeURIComponent(series)}/compress`, "POST", body, init);
  }

  /** POST /timeseries/{series}/retention */
  setRetentionPolicy(series: string, body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/timeseries/${encodeURIComponent(series)}/retention`, "POST", body, init);
  }

  /** POST /timeseries/{series}/benchmark */
  benchmarkTimeSeries(series: string, body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/timeseries/${encodeURIComponent(series)}/benchmark`, "POST", body, init);
  }

  /** POST /jobs */
  createBulkJob(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/jobs`, "POST", body, init);
  }

  /** GET /jobs */
  listBulkJobs(init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/jobs`, "GET", undefined, init);
  }

  /** GET /jobs/{job_id} */
  getBulkJob(jobId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/jobs/${encodeURIComponent(jobId)}`, "GET", undefined, init);
  }

  /** DELETE /jobs/{job_id} */
  cancelBulkJob(jobId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/jobs/${encodeURIComponent(jobId)}`, "DELETE", undefined, init);
  }

  /** POST /estimate-cost */
  estimateCost(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/estimate-cost`, "POST", body, init);
  }

  /** POST /replay */
  replayRequest(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/replay`, "POST", body, init);
  }

  /** POST /replay/batch */
  batchReplay(body?: unknown, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/replay/batch`, "POST", body, init);
  }

  /** GET /replay/logs */
  listRequestLogs(init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/replay/logs`, "GET", undefined, init);
  }

  /** GET /replay/logs/{log_id} */
  getRequestLog(logId: string, init?: RequestInit): Promise<Response> {
    return this.request(`${this.baseUrl}/replay/logs/${encodeURIComponent(logId)}`, "GET", undefined, init);
  }
}
