#!/usr/bin/env node
/**
 * Issue #347 — generate a TypeScript client from `docs/openapi.yaml`.
 *
 * Emits `clients/typescript/src/client.ts`: a dependency-free `fetch` wrapper
 * with one method per declared operation (keyed by `operationId`), typed path
 * parameters, and a configurable `baseUrl` / auth token. Request/response body
 * types are surfaced as `unknown` — this generator covers the call surface,
 * not full schema codegen.
 *
 * Usage: node scripts/generate_ts_client.mjs [--check]
 *   --check  fail if the committed client is stale instead of writing it.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(repoRoot, "clients/typescript/src/client.ts");
const HTTP_METHODS = ["get", "put", "post", "delete", "patch"];
const checkOnly = process.argv.includes("--check");

function parsePaths(yaml) {
  /** @type {Array<{path:string, method:string, operationId:string}>} */
  const ops = [];
  let inPaths = false;
  let currentPath = null;
  let currentMethod = null;
  for (const raw of yaml.split(/\r?\n/)) {
    const line = raw.replace(/\s+$/, "");
    if (!line.trim() || line.trim().startsWith("#")) continue;
    const indent = line.length - line.trimStart().length;
    const t = line.trimStart();
    if (indent === 0) {
      inPaths = line.startsWith("paths:");
      currentPath = currentMethod = null;
      continue;
    }
    if (!inPaths) continue;
    if (indent === 2 && t.startsWith("/") && t.endsWith(":")) {
      currentPath = t.slice(0, -1);
      currentMethod = null;
    } else if (indent === 4 && t.endsWith(":")) {
      const key = t.slice(0, -1).toLowerCase();
      currentMethod = HTTP_METHODS.includes(key) ? key : null;
      if (currentMethod) {
        ops.push({
          path: currentPath,
          method: currentMethod,
          operationId: defaultOpId(currentMethod, currentPath),
        });
      }
    } else if (indent === 6 && t.startsWith("operationId:") && currentMethod) {
      ops[ops.length - 1].operationId = t.slice("operationId:".length).trim();
    }
  }
  return ops;
}

function defaultOpId(method, path) {
  const parts = path
    .split("/")
    .filter(Boolean)
    .map((s) => s.replace(/[{}]/g, ""))
    .map((s) => s.replace(/[^A-Za-z0-9]+/g, " ").trim())
    .map((s) => s.replace(/\s+(.)/g, (_, c) => c.toUpperCase()));
  return method + parts.map((p) => p[0].toUpperCase() + p.slice(1)).join("");
}

function pathParams(path) {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
}

function renderMethod({ path, method, operationId }) {
  const params = pathParams(path);
  const args = params.map((p) => `${toCamel(p)}: string`);
  const hasBody = method !== "get" && method !== "delete";
  if (hasBody) args.push("body?: unknown");
  args.push("init?: RequestInit");
  const template =
    "`${this.baseUrl}" +
    path.replace(/\{([^}]+)\}/g, (_, p) => "${encodeURIComponent(" + toCamel(p) + ")}") +
    "`";
  return `  /** ${method.toUpperCase()} ${path} */
  ${operationId}(${args.join(", ")}): Promise<Response> {
    return this.request(${template}, "${method.toUpperCase()}"${hasBody ? ", body" : ", undefined"}, init);
  }`;
}

function toCamel(s) {
  return s.replace(/[_-]+(.)/g, (_, c) => c.toUpperCase());
}

const ops = parsePaths(readFileSync(join(repoRoot, "docs/openapi.yaml"), "utf8"));
const generated = `// AUTO-GENERATED by scripts/generate_ts_client.mjs from docs/openapi.yaml.
// Do not edit by hand. Run \`node scripts/generate_ts_client.mjs\` to regenerate.
// Covers ${ops.length} operations.

export interface ClientOptions {
  baseUrl?: string;
  token?: string;
}

export class EthosApiClient {
  readonly baseUrl: string;
  private readonly token?: string;

  constructor(opts: ClientOptions = {}) {
    this.baseUrl = (opts.baseUrl ?? "http://localhost:3000").replace(/\\/$/, "");
    this.token = opts.token;
  }

  private request(url: string, method: string, body: unknown, init?: RequestInit): Promise<Response> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (this.token) headers["authorization"] = \`Bearer \${this.token}\`;
    return fetch(url, {
      method,
      headers: { ...headers, ...(init?.headers as Record<string, string>) },
      body: body === undefined ? undefined : JSON.stringify(body),
      ...init,
    });
  }

${ops.map(renderMethod).join("\n\n")}
}
`;

if (checkOnly) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== generated) {
    console.error(
      "TypeScript client is stale. Run: node scripts/generate_ts_client.mjs",
    );
    process.exit(1);
  }
  console.log("TypeScript client is up to date.");
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, generated);
  console.log(`Wrote ${OUT} (${ops.length} operations).`);
}
