#!/usr/bin/env bash
# scripts/install-hooks.sh
#
# Installs git hooks for the ethos-contracts-backend project.
#
# Currently installs:
#   • pre-commit — secret scanning via gitleaks (scripts/pre-commit-secret-scan.sh)
#
# Run this once after cloning the repository:
#   ./scripts/install-hooks.sh
#
# The script is idempotent: running it multiple times is safe, and it will
# repair a partially-failed installation (e.g. a hook file that exists but
# lost its executable bit) on re-run.

set -euo pipefail

# ─── Colour helpers ───────────────────────────────────────────────────────────
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# ─── Resolve paths ────────────────────────────────────────────────────────────
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [[ -z "${REPO_ROOT}" ]]; then
  echo -e "${RED}Error: must be run inside a git repository.${RESET}" >&2
  exit 1
fi

HOOKS_DIR="${REPO_ROOT}/.git/hooks"
SCRIPTS_DIR="${REPO_ROOT}/scripts"

# ─── Expected hooks registry ──────────────────────────────────────────────────
# name -> source script, kept as parallel arrays for portability (macOS ships
# an old bash without associative arrays by default).
EXPECTED_HOOK_NAMES=("pre-commit")
EXPECTED_HOOK_SOURCES=("${SCRIPTS_DIR}/pre-commit-secret-scan.sh")

# Tracks per-hook install outcome for the final summary.
INSTALL_RESULTS=()

# ─── Ensure the hooks directory exists ────────────────────────────────────────
mkdir -p "${HOOKS_DIR}"

# ─── Helper: install a single hook ────────────────────────────────────────────
install_hook() {
  local hook_name="$1"        # e.g. "pre-commit"
  local source_script="$2"    # absolute path to the source script

  local hook_target="${HOOKS_DIR}/${hook_name}"

  if [[ ! -f "${source_script}" ]]; then
    echo -e "${RED}Error: source script not found: ${source_script}${RESET}" >&2
    INSTALL_RESULTS+=("${hook_name}:FAILED:source script missing")
    return 1
  fi

  # If a hook already exists and is NOT our script, back it up rather than
  # silently overwriting it (e.g. pre-existing hooks from other tools).
  if [[ -f "${hook_target}" ]]; then
    # Check whether it already points to our script (idempotency check)
    if grep -qF "$(basename "${source_script}")" "${hook_target}" 2>/dev/null; then
      # Already installed — but make sure the exec bit and source script
      # are still in the state we expect (repairs partial installs where
      # the wrapper exists but permissions got reset).
      chmod +x "${hook_target}"
      chmod +x "${source_script}" 2>/dev/null || true
      echo -e "${GREEN}✅ ${hook_name} hook is already installed — verified and up to date.${RESET}"
      INSTALL_RESULTS+=("${hook_name}:OK:already installed")
      return 0
    fi

    local backup="${hook_target}.bak.$(date +%Y%m%d%H%M%S)"
    echo -e "${YELLOW}⚠️  Existing ${hook_name} hook found — backing up to:${RESET}"
    echo -e "   ${CYAN}${backup}${RESET}"
    cp "${hook_target}" "${backup}"
  fi

  # Write a thin wrapper that delegates to the versioned script in scripts/.
  # Using a wrapper (rather than symlinking) means the hook survives the script
  # being moved without leaving a dangling symlink.
  if ! cat > "${hook_target}" <<HOOK_CONTENT
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Re-run scripts/install-hooks.sh to update.
exec "\$(git rev-parse --show-toplevel)/scripts/$(basename "${source_script}")" "\$@"
HOOK_CONTENT
  then
    echo -e "${RED}❌ Failed to write ${hook_name} hook (permissions issue?)${RESET}" >&2
    INSTALL_RESULTS+=("${hook_name}:FAILED:could not write hook file")
    return 1
  fi

  if ! chmod +x "${hook_target}" 2>/dev/null; then
    echo -e "${RED}❌ Failed to make ${hook_name} hook executable (permissions issue?)${RESET}" >&2
    INSTALL_RESULTS+=("${hook_name}:FAILED:chmod +x failed")
    return 1
  fi

  echo -e "${GREEN}✅ Installed ${hook_name} hook → ${hook_target}${RESET}"
  INSTALL_RESULTS+=("${hook_name}:OK:installed")
}

# ─── Post-install verification ────────────────────────────────────────────────
# Confirms each expected hook file exists on disk AND has the executable bit
# set. This catches partial failures (e.g. install_hook silently no-op'd due
# to an earlier `set -e` exit, or a filesystem that doesn't support chmod).
verify_hook() {
  local hook_name="$1"
  local hook_target="${HOOKS_DIR}/${hook_name}"

  if [[ ! -f "${hook_target}" ]]; then
    echo -e "${RED}❌ Verification failed: ${hook_target} does not exist.${RESET}" >&2
    return 1
  fi

  if [[ ! -x "${hook_target}" ]]; then
    echo -e "${RED}❌ Verification failed: ${hook_target} is not executable.${RESET}" >&2
    return 1
  fi

  return 0
}

# ─── Install hooks ────────────────────────────────────────────────────────────
echo -e "${CYAN}${BOLD}Installing git hooks for ethos-contracts-backend…${RESET}"
echo ""

overall_failure=0

for i in "${!EXPECTED_HOOK_NAMES[@]}"; do
  name="${EXPECTED_HOOK_NAMES[$i]}"
  source="${EXPECTED_HOOK_SOURCES[$i]}"
  if ! install_hook "${name}" "${source}"; then
    overall_failure=1
  fi
done

# Make the source scripts themselves executable (in case they were checked
# out without the execute bit, which can happen on some systems or after a
# fresh clone).
for source in "${EXPECTED_HOOK_SOURCES[@]}"; do
  chmod +x "${source}" 2>/dev/null || true
done

echo ""
echo -e "${CYAN}${BOLD}Verifying installed hooks…${RESET}"
echo ""

verify_failure=0
for name in "${EXPECTED_HOOK_NAMES[@]}"; do
  if verify_hook "${name}"; then
    echo -e "${GREEN}✅ Verified: ${name} exists and is executable.${RESET}"
  else
    verify_failure=1
  fi
done

# ─── Summary ───────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}Installation Summary${RESET}"
echo -e "${CYAN}─────────────────────${RESET}"
for result in "${INSTALL_RESULTS[@]}"; do
  IFS=':' read -r name status detail <<< "${result}"
  if [[ "${status}" == "OK" ]]; then
    echo -e "  ${GREEN}✅ ${name}${RESET} — ${detail}"
  else
    echo -e "  ${RED}❌ ${name}${RESET} — ${detail}"
  fi
done
echo ""

if [[ "${overall_failure}" -eq 1 || "${verify_failure}" -eq 1 ]]; then
  echo -e "${RED}${BOLD}Some hooks failed to install or verify.${RESET}"
  echo -e "Common causes: read-only .git/hooks directory, insufficient permissions,"
  echo -e "or a filesystem that does not support the executable bit."
  echo -e "Fix the underlying issue (e.g. ${CYAN}chmod u+w ${HOOKS_DIR}${RESET}) and re-run:"
  echo -e "  ${CYAN}./scripts/install-hooks.sh${RESET}"
  echo -e "This script is idempotent and safe to re-run to fix partial installs."
  exit 1
fi

echo -e "${GREEN}${BOLD}All hooks installed and verified successfully.${RESET}"
echo ""
echo -e "The ${CYAN}pre-commit${RESET} hook will now scan staged files for secrets before"
echo -e "every ${CYAN}git commit${RESET}. If gitleaks is not installed it will warn but"
echo -e "not block the commit — CI will catch secrets before merge."
echo ""
echo -e "For more details see ${CYAN}docs/secret-scanning.md${RESET}."
