[package]
name = "ttl-vault"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "27.0.3", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "27.0.3", features = ["testutils"] }
proptest = { version = "1.4", default-features = false, features = ["std"] }
